version: '3.8'

services:
  bahar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bahar-app
    ports:
      - "8501:8501"
    volumes:
      # Model cache volumes (persistent across restarts)
      - ./volumes/transformers_cache:/app/cache/transformers
      - ./volumes/huggingface_cache:/app/cache/huggingface
      - ./volumes/torch_cache:/app/cache/torch
      - ./volumes/nltk_data:/app/cache/nltk_data
      - ./volumes/spacy_data:/app/cache/spacy_data

      # Configuration and data (persistent)
      - ./config:/app/config
      - ./volumes/app_data:/app/data
      - ./bahar:/app/bahar

      # Optional: Mount docs for live updates during development
      # - ./docs:/app/docs:ro
    environment:
      # Cache directories
      - TRANSFORMERS_CACHE=/app/cache/transformers
      - HF_HOME=/app/cache/huggingface
      - TORCH_HOME=/app/cache/torch
      - NLTK_DATA=/app/cache/nltk_data
      - SPACY_DATA=/app/cache/spacy_data

      # Streamlit configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false

      # Python optimization
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - bahar-network
    # Resource limits (adjust based on your server)
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G

networks:
  bahar-network:
    driver: bridge

