[project]
name = "bahar"
version = "0.2.0"
description = "Multilingual emotion classification using GoEmotions taxonomy"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "transformers>=4.57.0",
    "torch>=2.9.0",
    "rich>=14.2.0",
]
